### ISSUE TITLE
wifi_status() method throws exception

### ISSUE THREAD

**Issue by dzimmanck** [tonymitchell/rfa-eagle-api#1]
![image](https://user-images.githubusercontent.com/16160230/70823255-4ba9b580-1d94-11ea-95e7-de8b17b07f20.png)

**Comment by tonymitchell** [comment]
It looks like they have added some new attributes in the latest software version.  I was able to reproduce this error on version 3.8.0.442.

**Comment by tonymitchell** [comment]
#2 Accepted PR to fix this issue.
